### ISSUE TITLE
міксини

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/FreshCode#49]
https://github.com/TarasOstasha/FreshCode/blob/4c9447c7d437f79708a29b87be600a5d6b334d08/user-list/src/components/CurrentWeather/weather.module.scss#L4
- респект за використання міксинів, але, оскільки тут нема параметрів, то краще підійшло б розширення.
З фрагмента поточного кода на виході отримається 
```css
.weatherWrapper .generalSection {
  padding: 10px;
  display: flex; /* 1 */
  align-items: center; /* 2 */
  justify-content: center; /* 3 */
  flex-wrap: wrap;
}
.weatherWrapper .generalSection .generalSectionSub {
  display: flex; /* 1 */
  align-items: center; /* 2 */
  justify-content: center; /* 3 */
} 
``` 
тобто рядки 1, 2, 3 повторюються один в один.
В таких випадках краще, щоб повторень не було і отримати щось типу
```css
.weatherWrapper .generalSection .generalSectionSub, .weatherWrapper .generalSection {
  display: flex;
  align-items: center;
  justify-content: center;
}

.weatherWrapper .generalSection {
  padding: 10px;
  flex-wrap: wrap;
}
``` 
Це якраз можливо розширеннями:
```css
%flexGeneralBeh {
    display: flex;
    align-items: center;
    justify-content: center;
}

.weatherWrapper {
    .generalSection {
        padding: 10px;
        @extend %flexGeneralBeh;
        flex-wrap: wrap;

        .generalSectionSub {
            @extend %flexGeneralBeh;
        }
    }
}
``` 
(вкладеності тут також зайві, але не стала прибирати, щоб не ускладнювати сприйняття).
При написанні sass коду можна певний час конвертувати в css, щоб перевірити, що буде на виході (https://www.sassmeister.com/, https://sass-lang.com/playground/).
